# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_article_autor_blog_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
    ]
