# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20171116_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='labels',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=' ', verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='None', max_length=255, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
